#!/usr/bin/env bash
#pings an ip adress that it recieved as an argument 5 times
ipaddress=$1
if [ -z "$ipaddress" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$ipaddress"
fi
